mysql:
  # 主数据库
  source:
    driverName: mysql
    host: 127.0.0.1
    port: 3306
    database: r2tiktok_db
    username: root
    password: xin051606
    charset: utf8mb4

  # 从数据库
  replica1:
    driverName: mysql
    host: 127.0.0.1
    port: 3306
    database: r2tiktok_db_1
    username: root
    password: xin051606
    charset: utf8mb4
  replica2:
    driverName: mysql
    host: 127.0.0.1
    port: 3306
    database: r2tiktok_db_2
    username: root
    password: xin051606
    charset: utf8mb4