server:
  name: "FeedServer"
  host: 0.0.0.0
  port: 8082

rpc:
  host: 127.0.0.1
  port: 66662

JWT:
  signingKey: "r2tiktokSigningKey"

etcd:
  host: 0.0.0.0
  port: 2379

video:
  maxSizeLimit: 60

# password:
#   salt: "jbzx"